steps:
- name: 'hashicorp/terraform:light'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Initializing Terraform..."
    terraform init
    echo "Applying Terraform configuration..."
    terraform apply -auto-approve

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Deploying Cloud Function..."
    gcloud functions deploy visitorCounterFunction \
      --region=us-central1 \
      --runtime=python311 \
      --trigger-http \
      --source=. \
      --entry-point=visitor_counter

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
