steps:
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      terraform init
      terraform apply -auto-approve
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'functions'
    - 'deploy'
    - 'visitorCounterFunction'
    - '--region=us-central1'
    - '--runtime=python311'
    - '--trigger-http'
    - '--source=.'
    - '--entry-point=visitor_counter'

timeout: '900s'